[versions]
agp = "8.3.2"
kotlin = "2.0.21"
kotlinCoroutinesAndroidVersion = "1.9.0"
kotlinCoroutinesCoreVersion = "1.9.0"
composeBom = "2024.11.00"
#--------------基础库相关-----------------
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
material = "1.12.0"
multidex = "2.0.1"
appcompat = "1.7.0"
gson = "2.11.0"
datastore = "1.1.1"
#--------------工具相关-----------------
interval = "1.0.3"
utilcodex = "1.31.1"
agentweb = "v5.1.1-androidx"
xxpermissions = "20.0"
glideVersion = "4.16.0"
landscapistGlide = "2.3.6"
logger = "2.2.0"
#--------------KTX相关-----------------
coreKtx = "1.15.0"
activityKtx = "1.9.3"
fragmentKtx = "1.8.5"
lifecycleKtx = "2.8.7"
#--------------Compose相关-----------------
coilCompose = "3.0.4"
constraintLayoutCompose = "1.1.0"
accompanist = "0.36.0"
googleAccompanistInsets = "0.31.5-beta"
navigationComposeVersion = "2.8.3"
paging = "3.3.4"
composeSmartrefreshVersion = "2.1.0"
any_pop_dialog_compose = "1.0.4"
composeviews = "1.7.0.1"
composeWebviewVersion = "0.33.6"
#--------------网络相关-----------------
retrofit = "2.11.0"
okhttpVersion = "5.0.0-alpha.14"
logginginterceptor = "v1.6.14"
cookiejarVersion = "v1.0.1"
converterGson = "2.11.0"
progressmanagerVersion = "1.5.0"
chucker = "4.0.0"
spiderman = "v1.1.8"
#--------------XML相关-----------------
eventbus = "3.3.1"
constraintlayout = "2.2.0"
recyclerviewVersion = "1.3.2"
viewpager2 = "1.1.0"
immersionbar = "3.0.0"
magicindicator = "1.7.0"
refreshHeader = "2.0.1"
refreshLayout = "2.0.1"
easynavigationVersion = "2.0.5"
xpopup = "2.1.16"
brvah = "3.0.7"

[libraries]
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinCoroutinesAndroidVersion" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinCoroutinesCoreVersion" }
#-----------------------------------------------基础库相关-------------------------------------------------------------
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-multidex = { module = "androidx.multidex:multidex", version.ref = "multidex" }
androidx-datastore = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
androidx-paging-common = { module = "androidx.paging:paging-common", version.ref = "paging" }
androidx-paging-runtime = { module = "androidx.paging:paging-runtime", version.ref = "paging" }
#-----------------------------------------------KTX相关-------------------------------------------------------------
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activityKtx" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleKtx" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleKtx" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycleKtx" }
#-----------------------------------------------图片加载相关-------------------------------------------------------------
coil = { module = "io.coil-kt.coil3:coil", version.ref = "coilCompose" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coilCompose" }
coil-compose-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coilCompose" }
github-glide = { module = "com.github.bumptech.glide:glide", version.ref = "glideVersion" }
landscapist-glide = { module = "com.github.skydoves:landscapist-glide", version.ref = "landscapistGlide" }
#-----------------------------------------------Compose相关-------------------------------------------------------------
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityKtx" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-animation= { module = "androidx.compose.animation:animation",name = "animation" }
compose-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata", name="runtime-livedata" }

constraintlayout-compose = { module = "androidx.constraintlayout:constraintlayout-compose-android", version.ref = "constraintLayoutCompose" }
compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "navigationComposeVersion" }
compose-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycleKtx" }
compose-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleKtx" }
accompanist-pager-indicators = { module = "com.google.accompanist:accompanist-pager-indicators", version.ref = "accompanist" }
accompanist-placeholder = { module = "com.google.accompanist:accompanist-placeholder-material", version.ref = "accompanist" }
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }

ccompanist = { module = "com.google.accompanist:accompanist-insets", version.ref = "googleAccompanistInsets" }
compose-paging = { module = "androidx.paging:paging-compose", version.ref = "paging" }

composesmartrefresh = { module = "io.github.loren-moon:composesmartrefresh", version.ref = "composeSmartrefreshVersion" }
any_pop_dialog_compose = { module = "io.github.TheMelody:any_pop_dialog_compose", version.ref = "any_pop_dialog_compose" }
composeViews = { module = "io.github.ltttttttttttt:ComposeViews", version.ref = "composeviews" }
compose-webview = { module = "io.github.kevinnzou:compose-webview", version.ref = "composeWebviewVersion" }

#-----------------------------------------------网络相关-------------------------------------------------------------
okhttp3-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttpVersion" }
okhttp3-okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttpVersion" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGson" }
cookieJar = { module = "com.github.franmontiel:PersistentCookieJar", version.ref = "cookiejarVersion" }
chucker-no-op = { module = "com.github.chuckerteam.chucker:library-no-op", version.ref = "chucker" }
chucker = { module = "com.github.chuckerteam.chucker:library", version.ref = "chucker" }
progressmanager = { module = "me.jessyan:progressmanager", version.ref = "progressmanagerVersion" }
logginginterceptor = { module = "com.github.fengzhizi715:saf-logginginterceptor", version.ref = "logginginterceptor" }
spiderman = { module = "com.github.simplepeng.SpiderMan:spiderman", version.ref = "spiderman" }
#------------------------------------------------工具相关--------------------------------------------------------------
interval = { module = "com.github.liangjingkanji:Interval", version.ref = "interval" }
utilcodex = { module = "com.blankj:utilcodex", version.ref = "utilcodex" }
agentweb = { module = "io.github.justson:agentweb-core", version.ref = "agentweb" }
xxPermissions = { module = "com.github.getActivity:XXPermissions", version.ref = "xxpermissions" }
logger = { module = "com.orhanobut:logger", version.ref = "logger" }
#------------------------------------------------XML相关--------------------------------------------------------------
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerviewVersion" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
eventbus = { module = "org.greenrobot:eventbus", version.ref = "eventbus" }
androidx-viewpager2 = { module = "androidx.viewpager2:viewpager2", version.ref = "viewpager2" }
github-brvah = { module = "com.github.CymChad:BaseRecyclerViewAdapterHelper", version.ref = "brvah" }
immersionbar = { module = "com.gyf.immersionbar:immersionbar", version.ref = "immersionbar" }
easyNavigation = { module = "com.github.Vincent7Wong:EasyNavigation", version.ref = "easynavigationVersion" }
refresh-header = { module = "com.scwang.smart:refresh-header-classics", version.ref = "refreshHeader" }
refresh-layout = { module = "com.scwang.smart:refresh-layout-kernel", version.ref = "refreshLayout" }
xpopup = { module = "com.lxj:xpopup", version.ref = "xpopup" }
magicIndicator = { module = "com.github.hackware1993:MagicIndicator", version.ref = "magicindicator" }


[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

