[versions]
agp = "8.3.0"
kotlin = "1.9.0"
kotlinStdlib = "1.9.20"
kotlinCoroutinesAndroidVersion = "1.7.3"
kotlinCoroutinesCoreVersion = "1.7.3"
composeBom = "2023.08.00"
#--------------基础库相关-----------------
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
material = "1.10.0"
multidex = "2.0.1"
appcompat = "1.6.1"
gson = "2.10.1"
customviewPoolingContainer = "1.0.0"
customviewVersion = "1.2.0-alpha02"
glideVersion = "4.15.1"
justAgentweb = "4.1.4"
eventbus = "3.3.1"
utilcodex = "1.31.0"
datastore = "1.0.0"
#--------------KTX相关-----------------
coreKtx = "1.10.1"
activityKtx = "1.8.0"
fragmentKtx = "1.5.6"
lifecycleRuntimeKtx = "2.6.1"
lifecycleKtx = "2.2.0"
#--------------Compose相关-----------------
lifecycleRuntimeComposeVersion = "2.6.1"
activityCompose = "1.8.0"
coilCompose = "2.1.0"
coilVersion = "2.1.0"
constraintlayoutCompose = "1.1.0-alpha12"
accompanist = "0.33.1-alpha"
accompanistPlaceholder = "0.31.0-alpha"
googleAccompanistInsets = "0.31.5-beta"
navigationComposeVersion = "2.7.1"
pagingCommon = "3.1.1"
pagingComposeVersion = "1.0.0-alpha18"
pagingRuntime = "3.1.1"
lifecycleViewmodelCompose = "2.6.1"
composeSmartrefreshVersion = "1.2.1"
any_pop_dialog_compose = "1.0.1"
#--------------网络相关-----------------
retrofit = "2.9.0"
okhttpVersion = "5.0.0-alpha.10"
loggingInterceptorVersion = "5.0.0-alpha.10"
cookiejarVersion = "v1.0.1"
converterGson = "2.9.0"
progressmanagerVersion = "1.5.0"
chucker = "3.5.2"
spiderman = "v1.1.8"
#--------------XML相关-----------------
constraintlayout = "2.1.4"
recyclerviewVersion = "1.3.0"
viewpager2 = "1.1.0-beta01"
immersionbar = "3.0.0"
magicindicator = "1.7.0"
refreshHeader = "2.0.1"
refreshLayout = "2.0.1"
easynavigationVersion = "2.0.5"
xpopup = "2.1.16"
brvah = "3.0.7"

[libraries]
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlinStdlib" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinCoroutinesAndroidVersion" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinCoroutinesCoreVersion" }
#-----------------------------------------------基础库相关-------------------------------------------------------------
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-multidex = { module = "androidx.multidex:multidex", version.ref = "multidex" }
androidx-datastore = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
androidx-paging-common = { module = "androidx.paging:paging-common", version.ref = "pagingCommon" }
androidx-paging-runtime = { module = "androidx.paging:paging-runtime", version.ref = "pagingRuntime" }
#-----------------------------------------------KTX相关-------------------------------------------------------------
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activityKtx" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleKtx" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycleKtx" }
#-----------------------------------------------图片加载相关-------------------------------------------------------------
coil = { module = "io.coil-kt:coil", version.ref = "coilVersion" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilCompose" }
coil-gif = { module = "io.coil-kt:coil-gif", version.ref = "coilCompose" }
github-glide = { module = "com.github.bumptech.glide:glide", version.ref = "glideVersion" }
#-----------------------------------------------Compose相关-------------------------------------------------------------
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
constraintlayout-compose = { module = "androidx.constraintlayout:constraintlayout-compose-android", version.ref = "constraintlayoutCompose" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationComposeVersion" }
lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycleRuntimeComposeVersion" }
composesmartrefresh = { module = "io.github.loren-moon:composesmartrefresh", version.ref = "composeSmartrefreshVersion" }
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelCompose" }
accompanist-pager-indicators = { module = "com.google.accompanist:accompanist-pager-indicators", version.ref = "accompanist" }
accompanist-placeholder = { module = "com.google.accompanist:accompanist-placeholder-material", version.ref = "accompanistPlaceholder" }
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }
accompanist-swiperefresh = { module = "com.google.accompanist:accompanist-swiperefresh", version.ref = "accompanist" }
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
ccompanist = { module = "com.google.accompanist:accompanist-insets", version.ref = "googleAccompanistInsets" }
androidx-paging-compose = { module = "androidx.paging:paging-compose", version.ref = "pagingComposeVersion" }
androidx-customview-poolingcontainer = { module = "androidx.customview:customview-poolingcontainer", version.ref = "customviewPoolingContainer" }
androidx-customview = { module = "androidx.customview:customview", version.ref = "customviewVersion" }
any_pop_dialog_compose = { module = "io.github.TheMelody:any_pop_dialog_compose", version.ref = "any_pop_dialog_compose" }
#-----------------------------------------------网络相关-------------------------------------------------------------
okhttp3-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptorVersion" }
okhttp3-okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttpVersion" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGson" }
cookieJar = { module = "com.github.franmontiel:PersistentCookieJar", version.ref = "cookiejarVersion" }
chucker-no-op = { module = "com.github.chuckerteam.chucker:library-no-op", version.ref = "chucker" }
chucker = { module = "com.github.chuckerteam.chucker:library", version.ref = "chucker" }
progressmanager = { module = "me.jessyan:progressmanager", version.ref = "progressmanagerVersion" }
spiderman = { module = "com.github.simplepeng.SpiderMan:spiderman", version.ref = "spiderman" }
#------------------------------------------------工具相关--------------------------------------------------------------
eventbus = { module = "org.greenrobot:eventbus", version.ref = "eventbus" }
utilcodex = { module = "com.blankj:utilcodex", version.ref = "utilcodex" }
#------------------------------------------------XML相关--------------------------------------------------------------
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerviewVersion" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-viewpager2 = { module = "androidx.viewpager2:viewpager2", version.ref = "viewpager2" }
github-brvah = { module = "com.github.CymChad:BaseRecyclerViewAdapterHelper", version.ref = "brvah" }
immersionbar = { module = "com.gyf.immersionbar:immersionbar", version.ref = "immersionbar" }
magicIndicator = { module = "com.github.hackware1993:MagicIndicator", version.ref = "magicindicator" }
easyNavigation = { module = "com.github.Vincent7Wong:EasyNavigation", version.ref = "easynavigationVersion" }
refresh-header = { module = "com.scwang.smart:refresh-header-classics", version.ref = "refreshHeader" }
refresh-layout = { module = "com.scwang.smart:refresh-layout-kernel", version.ref = "refreshLayout" }
agentweb = { module = "com.just.agentweb:agentweb", version.ref = "justAgentweb" }
xpopup = { module = "com.lxj:xpopup", version.ref = "xpopup" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

